Algoritmo "02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Programa que Leia um nome que e MOstre a Saldaçao
// Autor(a)    : Ruan Rodrigues
// Data atual  : 04/09/2022
Var
// Seção de Declarações das variáveis 
   Nome:caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite seu nome: ")
   Leia(Nome)
   Escreval("Olá ", Nome, " é Praser te conhecer ")
Fimalgoritmo