Algoritmo "09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   :Conversor de moedas real para dola
// Autor(a)    : Ruan Rodrigues
// Data atual  : 05/09/2022
Var
// Seção de Declarações das variáveis 
   N,D,Camb:Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o  valor: ")
   Leia(N)
   Camb <- 5,18
   D <- N/Camb
   Escreval("O valor digitado",N," é convertido em U$: ",D)
Fimalgoritmo