Algoritmo "39"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Algoritimmo de contagem de 10 até 3
// Autor(a)    : Ruan Rodrigues
// Data atual  : 14/09/2022
Var
// Seção de Declarações das variáveis 
   C:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   C <- 10
   Enquanto (C >= 3) faca
      Escreval(C)
      C <- C - 1
   FimEnquanto
   Escreval("Acbou!")

Fimalgoritmo