Algoritmo "41"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : função:fazer uma cotagem de 100 até 0 saltando 5
// Autor(a)    : Ruan Rodrigues
// Data atual  : 14/09/2022
Var
// Seção de Declarações das variáveis 
   C,N:Inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   C <- 100
   Enquanto (C >= 0) faca
      Escreval(C)
      C <- C - 5
   FimEnquanto
   Escreval("Acabou!")

Fimalgoritmo